#!/bin/bash
#set defaults
UNIT="w"
LENGTH="2"

#switch case depending on unit
case $1 in
  -d| --d)
    UNIT="d"
    LENGTH="$2"
    ;;
  -w| --week)
    UNIT="w"
    LENGTH="$2"
    ;;
  -m| --month)
    UNIT="m"
    LENGTH="$2"
    ;;
  -a| --all)
    UNIT="a"
    ;;
  -*|--*)
    echo "Unknown option: $1"
    exit 1
    ;;
  *)
    ;;
esac

#launch python app
/usr/local/lib/arp-network-scanner/venv3/bin/python3 /usr/local/lib/arp-network-scanner/evaluate.py ${UNIT} ${LENGTH}